version: 2

sources:
  - name: warehouse
    database: "{{ env_var('GCP_PROJECT_ID') }}" # Injected via CI
    schema: "data_warehouse_dev"
    tables:
      - name: raw_transactions

models:
  - name: stg_transactions
    description: "Cleaned transaction data with duplicates removed"
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: amount
        tests:
          - not_null
          # Custom Test: Amount must be positive
          - expression: ">= 0"

  - name: fct_daily_revenue
    description: "Daily revenue aggregation"
    columns:
      - name: total_revenue
        tests:
          - not_null